beauty_salon/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auth_views.LoginView.as_view(), 
          name='login'),
    path('main/', include('main_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                         document_root=settings.MEDIA_ROOT)

main_app/urls.py
from django.urls import path
from . import views
app_name = 'main'

urlpatterns = [
    path('procedure/category', views.ProcedureCategoryView.as_view(),
     name='procedure_category'),
    path('procedure/list/<int:category>', views.ProcedureListView.as_view(),
     name='procedure_list'),
    path('procedure/detail/<int:pk>', views.ProcedureDetailView.as_view(),
     name='procedure_detail'),
    path('procedure/schedule/list/<int:pk>', views.ScheduleView.as_view(),
     name='schedule_list'),
    path('procedure/my/schedule/list', views.MyScheduleView.as_view(),
     name='my_schedule'),
    path('procedure/record/save/', views.RecordSaveView.as_view(),
     name='record_save'),
    path('procedure/record/cancel/<pk>', views.RecordCancelView.as_view(),
         name='record_cancel'),
    path('favorite/', views.AddRemoveFavoriteProcedure.as_view(),name='favorite'),
    path('category/filter/', views.ProcedureCategoryFilterView.as_view(),name='category_filter'),
    path('substruction/', views.SubstructionView.as_view(),name='substruction'),
    path('profile/', views.ProfileView.as_view(),name='profile'),
    path('register/', views.RegistrationView.as_view(),name='register'),
    path('edit_profile/', views.EditProfileView.as_view(), name='edit_profile'),

]

main_app/models.py
from django.db import models
from django.conf import settings

class ProcedureCategory(models.Model):
    CATEGORY_TYPE = (
        (1, "Процедуры"),
        (2, "Салоны"),
    )
    title = models.CharField(max_length=50)
    img = models.ImageField(upload_to='images')
    category_type = models.IntegerField(choices=CATEGORY_TYPE)

    def __str__(self):
        return self.title

class Procedure(models.Model):
    title = models.CharField(max_length=100)
    img = models.ImageField(upload_to='images')
    description = models.TextField()
    category = models.ForeignKey(ProcedureCategory, on_delete=models.CASCADE)
    address = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=100)
    duration = models.IntegerField()
    limit = models.IntegerField()

    def __str__(self):
        return self.title 

class ImageProcedure(models.Model):
    procedure = models.ForeignKey(Procedure, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='images')

    def __str__(self):
        return self.procedure.title 

class ServiceProcedure(models.Model):
    procedure = models.ForeignKey(Procedure, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

class Schedule(models.Model):
    date = models.DateField()
    time = models.TimeField()
    procedure = models.ForeignKey(Procedure, on_delete=models.CASCADE)
    places_left = models.IntegerField()
    


class ProcedureLimit(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    procedure = models.ForeignKey(Procedure, on_delete=models.CASCADE)
    limit = models.IntegerField()

class Record(models.Model):
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    is_canceled = models.BooleanField(default=False)

class FavoriteProcedure(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    procedure = models.ForeignKey(Procedure, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

class Subscription(models.Model):
    title = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    def __str__(self):
        return self.title

class Customer(models.Model):
    subscription = models.ForeignKey(Subscription, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    start = models.DateField(null=True, blank=True)
    end = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.user.username

    

templates/base.html
{% load static %}
<!doctype html>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title></title>
	<meta name="viewport" content="width=device-width, initial-scale=1  maximum-scale=1 user-scalable=no">
	<meta name="mobile-web-app-capable" content="yes">
	<meta name="HandheldFriendly" content="True">
	
	<link rel="shortcut icon" href="img/favicon.png">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/slick.css' %}">
	<link rel="stylesheet" href="{% static 'css/slick-theme.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.theme.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.transitions.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<style type="text/css">
	select{
		display: block;
		color: #000;
		border: 1px solid #D9D9D9;
	}
</style>
<body>

	
	

	<!-- faq -->
	{% block content %}

	{% endblock %}
	
	<!-- end faq -->	
	
	<!-- footer -->
	<div class="appBottomMenu">
        <a class="item" href="{% url 'main:procedure_category' %}">
        	<i class="fa fa-home d-block" aria-hidden="true"></i><span class="d-block">Лента</span></a>
		<a class="item" href="{% url 'main:substruction' %}">
			<i class="fa fa-credit-card d-block" aria-hidden="true"></i><span class="d-block">Абонемент</span></a>
		<a class="item" href="{% url 'main:my_schedule' %}">
			<i class="fa fa-calendar d-block" aria-hidden="true"></i><span class="d-block">Расписание</span></a>
		<a class="item" href="{% url 'main:profile' %}">
			<i class="fa fa-user d-block" aria-hidden="true"></i><span class="d-block">Профиль</span></a>
    </div>
	<!-- end footer -->
	
	<!-- script -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/materialize.min.js' %}"></script>
	<script src="{% static 'js/slick.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>

</body>
</html>

templates/my_schedule.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<style type="text/css">
	body{
		background-color: #f6f6f6
	}
</style>
<div class="main-wrapper">
	<div class="navbar">
		<div class="container">
			<div class="panel-control-left">
				<a href="faq.html#" data-activates="slide-out-left" class="sidenav-control-left">
					<div class="site-title">
						<h1>Мое расписание</h1>
					</div>
				</a>
			</div>
			<div class="site-title">
				
			</div>
			<div class="panel-control-right">
				<a href="faq.html#" data-activates="slide-out-right" class="sidenav-control-right">
					<i class="fa fa-sign-out" aria-hidden="true"></i>
				</a>
			</div>
		</div>
	</div>
	<div class="cart-section section-gap-top-30" style="margin-top: 80px">
	    <div class="container">

	    	<div class="patient-appointments-col">
	    		{% for record in records %}
	    		<div class="patient-widget">
	    			<div class="patient-top-details">
	    				<div>
	    					<span class="invoice-id">Booking Date - {{record.schedule.date}}</span>
	    				</div>
	    				<div>
	    					<span class="date-col"></span>
	    				</div>
	    			</div>
	    			<div class="invoice-widget">
	    				<div class="pat-info-left">
	    					<div class="patient-img">
	    						<a href="#">
	    							<img src="{{record.schedule.procedure.img.url}}" class="img-fluid" alt="User Image" style="width: 100%; height: 50px">
	    						</a>
	    					</div>
	    					<div class="pat-info-cont">
	    						<h4 class="pat-name"><a href="#">{{record.schedule.procedure.title}}</a></h4>
	    						<div class="patient-details-col">
	    							<span class="">Appt Date {{record.schedule.time}} / {{record.schedule.procedure.duration}} min</span>
	    						</div>
	    						<div class="hour-col">
	    							<div>
	    								<span class="hours">{{record.schedule.procedure.address}}</span>
	    							</div>
	    						</div>
	    					</div>
	    				</div>
	    			</div>
	    			<div class="status-col">
	    				{% if record.is_canceled %}							
	    					<a href="#" class="btn view-eye"><i><img src="assets/img/icon-awesome-eye.svg" alt=""></i>запись отменен</a>
						{% else %}
							<form action="{% url 'main:record_cancel' record.id %}" method="post">
								{% csrf_token %}
								<input type="submit" value="отменить запись" class="btn success">
							</form>
						{% endif %}
	    			</div>
	    		</div>
	    		{% endfor %}


	    	</div>
	    </div>
	</div>

</div>


{% endblock %}

templates/procedure_category.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<!-- navbar -->
<div class="navbar">
	<div class="container">
		<div class="panel-control-left">
			<a href="faq.html#" data-activates="slide-out-left" class="sidenav-control-left">
				<div class="site-title">
					<h1>Процедуры</h1>
				</div>
			</a>
		</div>
		<div class="site-title">
			
		</div>
		<div class="panel-control-right">
			<a href="faq.html#" data-activates="slide-out-right" class="sidenav-control-right">
				<i class="fa fa-sign-out" aria-hidden="true"></i>
			</a>
		</div>
	</div>
</div>
<div class="the-slider">
	<div class="container">
		<div class="the-slider-entry">
			<div class="slider-slick">
				<div class="slider-entry"><img src="{% static 'img/slider1.png' %}" alt="">
					<div class="overlay"></div>
					<div class="caption">
						<div class="container">
							<h2><a href="index.html">Great Shopping</a></h2>
							<p>Find your need now and get Discount</p>
						</div>
					</div>
				</div>
				<div class="slider-entry">
					<div class="overlay"></div><img src="{% static 'img/slider2.png' %}" alt="">
					<div class="caption">
						<div class="container">
							<h2>Limited Edition</h2>
							<p>Find your need now and get Discount</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="faq ">
	<div class="container">
		<!-- end navbar -->
		<div class="row">
			<div class="col-md-12">
				<select name="category_type" id="category-type-select" data-url="{% url 'main:category_filter' %}">
					<option value="1">Процедуры</option>
					<option value="2">Салоны</option>
				</select>
			</div>
		</div>
		<div style="padding-bottom: 50px;">
			<di id="procedure_category_list">
				{% include 'procedure_category_list.html' %}
			</di>
		</div>
	</div>
</div>	

{% endblock %}

templates/procedure_category_list.html
<div class="row" style="display: flex">
	{% for category in categories %}
	<div class="col s6">
		<div class="swiper-slide swiper-slide-active">
			<a href="{% url 'main:procedure_list' category.id %}" class="">
				<div class="half-mask"></div>
				<img src="{{category.img.url}}" alt="" style="width: 100%; height: 200px; border-radius: 15px">
				<div class="caption">
					<h4>{{category.title}}</h4>
					<span>{{category.procedure_set.count}}</span>
				</div>
			</a>
		</div>
	</div>
	{% endfor %}
</div>

templates/procedure_detail.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<div class="navbar">
	<div class="container">
		<div class="panel-control-left">
			<a href="faq.html#" data-activates="slide-out-left" class="sidenav-control-left">
				<div class="site-title">
					<h1>Процедуры</h1>
				</div>
			</a>
		</div>
		<div class="site-title">
			
		</div>
		<div class="panel-control-right">
			<a href="faq.html#" data-activates="slide-out-right" class="sidenav-control-right">
				<i class="fa fa-sign-out" aria-hidden="true"></i>
			</a>
		</div>
	</div>
</div>
<div class="product-details app-pages app-section">
	<div class="container">
		<div class="entry">
			<div class="row">
				<div class="col s12">
					<div class="the-slider" style="margin-top: 0">
						<div class="container">
							<div class="the-slider-entry">
							
								<div class="slider-slick">
									{% for image in procedure.imageprocedure_set.all %}
									<div class="slider-entry"><img src="{{image.img.url}}" alt="">
										<div class="overlay"></div>
										<div class="caption">
										</div>
									</div>
									{% endfor %}
								</div>
								
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="details">
			<h5>Перечень услуг</h5>
			<ul>
				{% for service in procedure.serviceprocedure_set.all %}
				<li>{{service.title}}<li>
				{% endfor %}
			</ul>
			<div class="price" style="margin-bottom: 15px"><h5>Осталось посещений:{{procedure_limit.limit}}</h5></div>
			<a href="{% url 'main:schedule_list' procedure.id %}" class="button">Расписание</a>
			<button id="favorite-button" data-url="{% url 'main:favorite' %}" data-procedure="{{ procedure.id }}" {% if is_favorite %}data-action="remove"{% else %}data-action="add"{% endif %}>
			  {% csrf_token %} {% if is_favorite %}Удалить из Избранного{% else %}Добавить в Избранное{% endif %}
			</button>
		</div>
	</div>
</div>
{% endblock %}

templates/procedure_list.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<div class="main-wrapper">
	<div class="navbar">
		<div class="container">
			<div class="panel-control-left">
				<a href="" data-activates="slide-out-left" class="sidenav-control-left">
					<div class="site-title">
						<h1>{{ category.title}}</h1>
					</div>
				</a>
			</div>
			<div class="site-title">
				
			</div>
			<div class="panel-control-right">
				<a href="faq.html#" data-activates="slide-out-right" class="sidenav-control-right">
					<i class="fa fa-sign-out" aria-hidden="true"></i>
				</a>
			</div>
		</div>
	</div>
	<div class="cart-section section-gap-top-30" style="margin-top: 80px">
	    <div class="container">
			<div class="block">
				{% for procedure in procedures %}
				<div class="content">
					<div class="image">
						<img src="{{procedure.img.url}}" alt="" style="height: 100px">
					</div>
					<div class="text">
						<a href="{% url 'main:procedure_detail' procedure.id %}"><h4>{{procedure.title}}</h4></a>
						<p class="location">
							<i class="icon ion-ios-pin"></i>
							{{procedure.address}}
						</p>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<div class="main-wrapper">
	<div class="navbar">
		<div class="container">
			<div class="panel-control-left">
				<a href="faq.html#" data-activates="slide-out-left" class="sidenav-control-left">
					<div class="site-title">
						<h1>Профиль</h1>
					</div>
				</a>
			</div>
			<div class="site-title">
				
			</div>
			<div class="panel-control-right">
				<a href="faq.html#" data-activates="slide-out-right" class="sidenav-control-right">
					<i class="fa fa-sign-out" aria-hidden="true"></i>
				</a>
			</div>
		</div>
	</div>
	<div class="blog-single app-pages app-section">
		<div class="container">
			<div class="entry">				<div class="author">
					<div class="entry">
						<strong><a href="#">{{request.user.first_name}}  {{request.user.last_name}}</a></strong>
						<ul>
							<li><a href="blog-single.html"><i class="fa fa-facebook-square"></i></a></li>
							<li><a href="blog-single.html"><i class="fa fa-twitter-square"></i></a></li>
							<li><a href="blog-single.html"><i class="fa fa-google-plus-square"></i></a></li>
							<li><a href="blog-single.html"><i class="fa fa-instagram"></i></a></li>
						</ul>
						<a href="{% url 'main:edit_profile' %}">Edit profile</a>
					</div>
				</div>
				<div class="comment">
					<h6>Процедуры</h6>
					{% for procedure in favorite_procedures %}
					<div class="content">
						<img src="{{procedure.procedure.img.url}}" alt="">
						<div class="entry">
							<strong><a href="{% url 'main:procedure_detail' procedure.procedure.id %}">{{procedure.procedure.title}}</a></strong>
							<p>{{procedure.procedure.address}}</p>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/profile_change.html
{% extends 'base.html' %}

{% block content %}
<div class="main-wrapper">
	<div class="navbar">
		<div class="container">
			<div class="panel-control-left">
				<a href="faq.html#" data-activates="slide-out-left" class="sidenav-control-left">
					<div class="site-title">
						<h1>Профиль</h1>
					</div>
				</a>
			</div>
			<div class="site-title">
				
			</div>
			<div class="panel-control-right">
				<a href="http://127.0.0.1:8000/" class="">
					<i class="fa fa-sign-out" aria-hidden="true"></i>
				</a>
			</div>
		</div>
	</div>
	<div class="blog-single app-pages app-section">
		<div class="container">
			<div class="post-comment">
				 <h2>Edit Profile</h2>
				<div class="content">
					<form method="post" style="width: 100%;">
				    {% csrf_token %}
				    {{ form.username }}<br>
				    {{ form.email }}<br>
				    {{ form.first_name }}<br>
				    {{ form.last_name }}<br>
				    <button type="submit" class="button">Save Changes</button>
				  </form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/schedule.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<style type="text/css">
	body{
		background-color: #f6f6f6
	}
</style>
<div class="main-wrapper">
	<div class="navbar">
		<div class="container">
			<div class="panel-control-left">
				<a href="faq.html#" data-activates="slide-out-left" class="sidenav-control-left">
					<div class="site-title">
						<h1>Расписание</h1>
					</div>
				</a>
			</div>
			<div class="site-title">
				
			</div>
			<div class="panel-control-right">
				<a href="faq.html#" data-activates="slide-out-right" class="sidenav-control-right">
					<i class="fa fa-sign-out" aria-hidden="true"></i>
				</a>
			</div>
		</div>
	</div>
	<div class="cart-section section-gap-top-30" style="margin-top: 80px">
	    <div class="container">
	    	<h4>{% regroup schedules by date as schedule_list %}</h4>
	    	<div class="patient-appointments-col">
	    		{% for schedule in schedule_list %}
	    		<h4 style="margin-bottom: 10px">{{ schedule.grouper }}</h4>
	    			{% for item in schedule.list %}
		    		<div class="patient-widget">
		    			<div class="invoice-widget">
		    				<div class="pat-info-left">
		    					<div class="pat-info-cont">
		    						<h4 class="pat-name"><a href="#">{{ item.procedure.title }}</a></h4>
		    						<div class="patient-details-col">
		    							<span class="">Appt Date {{ item.time }}
			{{ item.procedure.duration }} мин min</span>
		    						</div>
		    						<div class="hour-col">
		    							<div>
		    								<span class="hours">Осталость {{ item.places_left }} мест</span>
		    							</div>
		    						</div>
		    					</div>
		    				</div>
		    			</div>
		    			<div class="status-col">
		    				<form action="{% url 'main:record_save' %}" method="POST">
								{% csrf_token %}
								<input type="hidden" name="schedule" value="{{ item.id }}">
								<input type="hidden" name="user" value="{{ request.user.id }}">
								<input type="hidden" name="procedure" value="{{pk}}">
								<input type="submit" value="записаться" class="btn success">
							</form>
		    			</div>
		    		</div>
		    		{% endfor %}
	    		{% endfor %}


	    	</div>
	    </div>
	</div>

</div>
{% endblock %}

templates/substruction.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<div class="main-wrapper">
	<div class="navbar">
		<div class="container">
			<div class="panel-control-left">
				<a href="faq.html#" data-activates="slide-out-left" class="sidenav-control-left">
					<div class="site-title">
						<h1>Абонемент</h1>
					</div>
				</a>
			</div>
			<div class="site-title">
				
			</div>
			<div class="panel-control-right">
				<a href="faq.html#" data-activates="slide-out-right" class="sidenav-control-right">
					<i class="fa fa-sign-out" aria-hidden="true"></i>
				</a>
			</div>
		</div>
	</div>
	<div class="cart-section section-gap-top-30" style="margin-top: 80px">
		<div class="invoices">
			<div class="container">
				<div class="patient-widget">
					<div class="">
						<div>
							{{substruction.subscription.title}}
							{{substruction.subscription.price}}
							{% if substruction.start and substruction.end %}
							    <p>This subscription lasts {{ substruction.end|date:"F j, Y" }} - {{ substruction.start|date:"F j, Y" }} = {{ duration_str }} days.</p>
							{% else %}
							    <p>This subscription has not started yet.</p>
							{% endif %}
						</div>
						<div>
					</div>
					<div class="invoice-widget">
						<div class="pat-info-left">
							<div class="patient-img">
								<a href="#">
									<img src="{% static 'img/90.svg' %}" style="width: 100%" class="img-fluid" alt="User Image">
								</a>
							</div>
							<div class="pat-info-cont">
								<h4 class="pat-name"><a href="#">Subscriptions</a></h4>
								<div class="patient-details-col">
									<span>90 days KZT</span>
								</div>
							</div>
						</div>
						<div class="pat-info-right">
							<div class="price">7490 KZT * 12 month</div>
							<div class="view-btn">
								<a href="https://wa.me/77009555870">Купить сейчас</a>
							</div>
						</div>
					</div>
				</div>




			</div>
		</div>
	</div>
</div>
{% endblock %}